// ACTION TYPES
const CONNECT = 'CONNECT';

const DISCONNECT = 'DISCONNECT';

const SET_CONFIG = 'SET_CONFIG';

const SET_SENSOR_DATA = 'SET_SENSOR_DATA';

const SET_SPRINKLER_DATA = 'SET_SPRINKLER_DATA';

const SET_IRRIGATION_MINIMUM = 'SET_IRRIGATION_MINIMUM';

// EXPORT
export default {
  CONNECT,
  DISCONNECT,

  SET_CONFIG,

  SET_SENSOR_DATA,

  SET_SPRINKLER_DATA,

  SET_IRRIGATION_MINIMUM,
};
